export enum RelationshipType {
  PROPOSED_BY = "PROPOSED_BY",

  INTRODUCES = "INTRODUCES",

  ADDRESSES = "ADDRESSES",

  RESULTS_IN = "RESULTS_IN",

  IMPLEMENTED_IN = "IMPLEMENTED_IN",

  RELATED_TO = "RELATED_TO",

  SUPERSEDES = "SUPERSEDES"
}